server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db_comparison_diff
    username: root
    password: root


logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG